### PR TITLE
[NDK][NTOS] Add global definition of INIT_FUNCTION

### PR DESCRIPTION
**Pull request by tkreuzer**
* Add an NDK header to define INIT_FUNCTION/INIT_SECTION globally
* Use _declspec(allocate(x)) and _declspec(code_seg(x)) on MSVC versions that support it
* Use INIT_FUNCTION on functions only and INIT_SEGMENT on data only (required by MSVC)
* Place INIT_FUNCTION at the top (required by MSVC)
* Make sure declarations and implementations share the same modifiers (required by MSVC)
* Add a global linker option to suppress warnings about defined but unused INIT section
* Merge INIT section into .text in freeldr

TODO
- [x] Investigate Guru Meditation issue

### CODE REVIEW

**Comment by HBelusca** [comment]
Usually when we include NDK headers we do: `#include <ndk/the_header.h>`

File: ntoskrnl/ob/obinit.c [hunk 1]
```diff
@@ -55,9 +55,9 @@ ULONG ObpInitializationPhase;
 /* PRIVATE FUNCTIONS *********************************************************/
 
 static
+INIT_FUNCTION
```
[the remark this answers is not in the document]
Comment (tkreuzer) [reply ntoskrnl/ob/obinit.c]: No, both works fine.

File: sdk/cmake/msvc.cmake [hunk 2]
```diff
@@ -135,9 +135,9 @@ if(RUNTIME_CHECKS)
     add_compile_flags("/RTC1")
 endif()
 
-set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /MANIFEST:NO /INCREMENTAL:NO /SAFESEH:NO /NODEFAULTLIB /RELEASE ${_hotpatch_link_flag}")
-set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} /MANIFEST:NO /INCREMENTAL:NO /SAFESEH:NO /NODEFAULTLIB /RELEASE /IGNORE:4104 ${_hotpatch_link_flag}")
-set(CMAKE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS} /MANIFEST:NO /INCREMENTAL:NO /SAFESEH:NO /NODEFAULTLIB /RELEASE ${_hotpatch_link_flag}")
+set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /MANIFEST:NO /INCREMENTAL:NO /SAFESEH:NO /NODEFAULTLIB /RELEASE ${_hotpatch_link_flag} /IGNORE:4039")
+set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} /MANIFEST:NO /INCREMENTAL:NO /SAFESEH:NO /NODEFAULTLIB /RELEASE /IGNORE:4104 ${_hotpatch_link_flag} /IGNORE:4039")
```
Comment (ThFabba) [inline sdk/cmake/msvc.cmake]: This line already has an `/IGNORE` option, so it might be nicer to move the new one before the hotpatch flag to keep them together.

File: sdk/include/ndk/section_attribs.h [hunk 3]
```diff
@@ -0,0 +1,24 @@
+
```
Comment (ThFabba) [inline sdk/include/ndk/section_attribs.h]: Should this have the standard NDK header?

File: sdk/cmake/msvc.cmake (hunk 2 above)
Comment (tkreuzer) [reply sdk/cmake/msvc.cmake]: Fixed

File: sdk/include/ndk/section_attribs.h (hunk 3 above)
Comment (tkreuzer) [reply sdk/include/ndk/section_attribs.h]: Fixed

**Comment by binarymaster** [comment]
I've tested this PR using RosBE with GCC on Windows.

When starting bootcd.iso right after pressing Enter with "Press any key to boot from the ReactOS medium", VirtualBox instantly crashes with Guru Meditation message even before loading boot drivers.

Once I rolled back the commit and recompiled the source tree, Guru Meditation crash disappeared.

- Here is VirtualBox log: [VBox.log](https://github.com/reactos/reactos/files/2673934/VBox.log)

**Comment by tkreuzer** [comment]
I split the thing into multiple commits.
@binarymaster Can you please retest and revert back one by one until you find the guilty commit?

**Comment by binarymaster** [comment]
Beginning with 7a9f27a and later commits the build could not be completed due to this error:

```
FAILED: drivers/filesystems/mup/mup_pch.h.gch
In file included from ../drivers/filesystems/mup/mup.h:139:0:
../drivers/filesystems/mup/dfs.h:9:0: error: "INIT_FUNCTION" redefined [-Werror]

In file included from ../drivers/filesystems/mup/mup.h:8:0:
../sdk/include/ndk/section_attribs.h:24:0: note: this is the location of the previous definition
cc1.exe: all warnings being treated as errors
```

80687e5 is the last commit which I can build with RosBE gcc-win.

It boots and installs successfully without problems.

**Comment by tkreuzer** [comment]
@binarymaster I think I fixed it (both build and boot). Can you retest?

**Comment by binarymaster** [comment]
I've retested, now it compiles without errors.

Also it doesn't cause Guru Meditation crash anymore even with last commit! :open_mouth:  I successfully installed it, both 1st and 2nd stages went well, 3rd stage also loaded correctly, and shutdown with no problems.
