### PR TITLE
Fix msvc x86 warnings

### PR DESCRIPTION
**Pull request by tkreuzer**
This PR fixes all remaining MSVC x86 warnings in our code, disables them in 3rd-party code and turns all warnings (except static analysis warnings) into errors.

### CODE REVIEW

File: modules/rostests/winetests/riched20/CMakeLists.txt [hunk 1]
```diff
@@ -8,7 +8,7 @@ list(APPEND SOURCE
     txtsrv.c)
 
 if(MSVC)
-    set_property(SOURCE editor.c APPEND_STRING PROPERTY COMPILE_FLAGS " /w14189")
+    set_source_files_properties(editor.c PROPERTIES COMPILE_FLAGS /wd4189)
```
Comment (katahiromz) [inline modules/rostests/winetests/riched20/CMakeLists.txt:11]: Please insert a comment here.

**Review by katahiromz — COMMENTED** [review]
I don't recommend killing C4090 warnings.

File: dll/win32/ntmarta/CMakeLists.txt [hunk 2]
```diff
@@ -11,3 +11,8 @@ add_library(ntmarta MODULE ${SOURCE})
 set_module_type(ntmarta win32dll UNICODE)
 add_importlibs(ntmarta user32 advapi32 msvcrt kernel32 ntdll)
 add_cd_file(TARGET ntmarta DESTINATION reactos/system32 FOR all)
+
+if(MSVC)
+    # Disable warning C4267: '=': conversion from 'size_t' to 'USHORT', possible loss of data
+    target_compile_options(ntmarta PRIVATE /wd4267)
+endif()
```
Comment (binarymaster) [inline dll/win32/ntmarta/CMakeLists.txt:18]: ntmarta doesn't seem to be 3rd-party module, so maybe better just fix warnings.

**Review by binarymaster — COMMENTED** [review]
Typo in one of commits: `s/3r-party/3rd-party/`

File: sdk/cmake/msvc.cmake [hunk 3]
```diff
@@ -76,6 +76,10 @@ endif()
 # Generate Warnings Level 3
 add_compile_options(/W3)
 
+#if (NOT ARCH STREQUAL "amd64")
```
Comment (SergeGautherie) [inline sdk/cmake/msvc.cmake:79]:
```suggestion
if (ARCH STREQUAL "i386")
```

File: dll/directx/CMakeLists.txt [hunk 4]
```diff
@@ -1,4 +1,11 @@
 
+if (MSVC)
+    # Disable warning C4146: unary minus operator applied to unsigned type, result still unsigned
+    # Disable warning C4090: 'function': different 'const' qualifiers
+    add_compile_options(/wd4146 /wd4090)
+endif()
+
+
```
Comment (SergeGautherie) [inline dll/directx/CMakeLists.txt:8]:
```suggestion

```

File: dll/win32/dbghelp/CMakeLists.txt [hunk 5]
```diff
@@ -81,7 +81,7 @@ else()
     add_cd_file(TARGET dbghelp DESTINATION reactos/system32 FOR all)
 
     if(MSVC)
-        # Disable warning C4477 (printf format warnings)
-        remove_target_compile_option(dbghelp "/we4477")
-    endif()
+        # Disable warning C4146: unary minus operator applied to unsigned type, result still unsigned
+        target_compile_options(dbghelp PRIVATE /wd4146)
+   endif()
```
Comment (SergeGautherie) [inline dll/win32/dbghelp/CMakeLists.txt:86]:
```suggestion
    endif()
```

File: dll/win32/msi/CMakeLists.txt [hunk 6]
```diff
@@ -64,11 +64,10 @@ add_library(msi MODULE
...
 if(MSVC)
-    #  error C4133: 'function': incompatible types - from 'UINT *' to 'MSIINSTALLCONTEXT *'
-    remove_target_compile_option(msi "/we4133")
-
-    # error C4312: 'type cast': conversion from 'unsigned int' to 'HANDLE' of greater size
-    remove_target_compile_option(msi "/we4312")
+    # Disable warning C4133: 'function': incompatible types - from 'UINT *' to 'MSIINSTALLCONTEXT *'
+    # Disable warning C4090: 'function': different 'const' qualifiers
+    # Disable warning C4146: unary minus operator applied to unsigned type, result still unsigned
+    target_compile_options(msi PRIVATE /wd4133 /wd4090 /wd4146)
```
Comment (SergeGautherie) [inline dll/win32/msi/CMakeLists.txt:70]: Sort by increasing number. (Everywhere.)

**Comment by andrew-boyarshin** [comment]
Maybe it's better to turn warnings into errors only on CI builds? It's the same usual problem that exists on Linux distros: you want something unmaintained, you do the usual clone + configure + make only to get a compilation error. It might even be hard to remove the WX compiler flag (when you don't control the build process). We can safely assume that e.g. MSVC 29.13 finds more warnings in ReactOS, than 14.22 does. There is no need to make the life harder for someone in 2031 wanting to `git bisect` that sneaky regression in 0.4.15 while using his latest MSVC version.

File: base/applications/sndvol32/dialog.c [hunk 7]
```diff
@@ -373,7 +373,7 @@ LoadDialog(
     Offset++;
 
     /* calculate font length */
-    Length = wcslen((LPWSTR)Offset) + 1;
+    Length = (WORD)wcslen((LPWSTR)Offset) + 1;
```
Comment (zefklop) [inline base/applications/sndvol32/dialog.c:376]: Why don't you declare Length as size_t instead ?

File: base/services/wkssvc/wkssvc.c [hunk 8]
```diff
@@ -85,7 +85,7 @@ ServiceInit(VOID)
     GetVersionExW(&VersionInfo);
 
     ProcessName.Buffer = "Workstation";
-    ProcessName.Length = strlen(ProcessName.Buffer);
+    ProcessName.Length = (USHORT)strlen(ProcessName.Buffer);
```
Comment (zefklop) [inline base/services/wkssvc/wkssvc.c:88]: RtlInitUnicodeString ?

File: base/setup/lib/utils/osdetect.c [hunk 9]
```diff
@@ -320,7 +320,7 @@ CheckForValidPEAndVendor(
 
             RtlStringCbCopyNW(VendorName->Buffer, VendorName->MaximumLength,
                               pvData, BufLen * sizeof(WCHAR));
-            VendorName->Length = wcslen(VendorName->Buffer) * sizeof(WCHAR);
+            VendorName->Length = (USHORT)wcslen(VendorName->Buffer) * sizeof(WCHAR);
```
Comment (zefklop) [inline base/setup/lib/utils/osdetect.c:323]: We don't have `RtlUnicodeStringCbCopyStringN`, do we ?

File: dll/win32/msv1_0/msv1_0.c [hunk 10]
```diff
@@ -102,18 +102,25 @@ BuildInteractiveProfileBuffer(IN PLSA_CLIENT_REQUEST ClientRequest,
     PVOID ClientBaseAddress = NULL;
     LPWSTR Ptr;
     ULONG BufferLength;
+    SIZE_T ComputerNameLength;
     NTSTATUS Status = STATUS_SUCCESS;
 
     *ProfileBuffer = NULL;
     *ProfileBufferLength = 0;
 
+    ComputerNameLength = wcslen(ComputerName);
```
Comment (zefklop) [inline dll/win32/msv1_0/msv1_0.c:111]: `if (!NT_SUCCESS(RtlULongPtrToUShort(wcslen(ComputerName), &ComputerNameLength))))`
Please avoid all those cast that come afterwards.

**Comment by tkreuzer** [comment]
> 
> 
> I don't recommend killing C4090 warnings.

It's 3rd party code. Nobody is ever going to look at the warnings and wine is most likely not going to accept fixes anyway. So warnings are pretty useless.

File: base/applications/sndvol32/dialog.c (hunk 7 above)
Comment (tkreuzer) [reply base/applications/sndvol32/dialog.c:376]: Good question. Will fix.

File: base/services/wkssvc/wkssvc.c (hunk 8 above)
Comment (tkreuzer) [reply base/services/wkssvc/wkssvc.c:88]: Gonna use RTL_CONSTANT_STRING.

File: base/setup/lib/utils/osdetect.c (hunk 9 above)
Comment (tkreuzer) [reply base/setup/lib/utils/osdetect.c:323]: What would that do?

File: base/setup/usetup/spapisup/cabinet.c [hunk 11]
```diff
@@ -734,7 +734,7 @@ CabinetOpen(
         RemoveFileName(CabinetContext->CabinetPrev);
         CabinetNormalizePath(CabinetContext->CabinetPrev, 256);
         RtlInitAnsiString(&astring, (LPSTR)Buffer);
-        ustring.Length = wcslen(CabinetContext->CabinetPrev);
+        ustring.Length = (USHORT)wcslen(CabinetContext->CabinetPrev);
         ustring.Buffer = CabinetContext->CabinetPrev + ustring.Length;
         ustring.MaximumLength = sizeof(CabinetContext->CabinetPrev) - ustring.Length;
```
Comment (tkreuzer) [inline base/setup/usetup/spapisup/cabinet.c:739]: TBH, all of this looks super broken. Can anyone explain this to me? @HBelusca?

File: base/setup/lib/utils/osdetect.c (hunk 9 above)
Comment (HBelusca) [reply base/setup/lib/utils/osdetect.c:323]: > We don't have `RtlUnicodeStringCbCopyStringN`, do we ?

No we don't.

File: sdk/include/ndk/umtypes.h [hunk 12]
```diff
@@ -108,12 +108,12 @@ Header Name:
...
-#define MINSHORT                        (-32768)
-#define MAXSHORT                        32767
-#define MINLONG                         (-2147483648)
-#define MAXLONG                         2147483647
+#define MINCHAR                         0x80
+#define MAXCHAR                         0x7f
+#define MINSHORT                        0x8000
+#define MAXSHORT                        0x7fff
+#define MINLONG                         0x80000000
+#define MAXLONG                         0x7fffffff
```
Comment (zefklop) [inline sdk/include/ndk/umtypes.h:116]: With `L` suffix maybe ? At least for the 32bits values.

File: base/setup/lib/utils/osdetect.c (hunk 9 above)
Comment (zefklop) [reply base/setup/lib/utils/osdetect.c:323]: > What would that do?

Copy a string into a UNICODE_STRING, as name suggests :slightly_smiling_face: 
https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntstrsafe/nf-ntstrsafe-rtlunicodestringcbcopystringn

File: base/setup/lib/utils/regutil.c [hunk 13]
```diff
@@ -78,7 +78,7 @@ CreateNestedKey(PHANDLE KeyHandle,
             break;
         }
         *Ptr = (WCHAR)0;
-        LocalKeyName.Length = wcslen(LocalKeyName.Buffer) * sizeof(WCHAR);
+        LocalKeyName.Length = (USHORT)wcslen(LocalKeyName.Buffer) * sizeof(WCHAR);
```
Comment (zefklop) [inline base/setup/lib/utils/regutil.c:81]: `LocalKeyName.Length = Ptr - LocalKeyName.Buffer

File: sdk/include/ndk/umtypes.h (hunk 12 above)
Comment (tkreuzer) [reply sdk/include/ndk/umtypes.h:116]: There is no reason for it, because on Windows both long and int are 32 bit, so there is no difference (unless you have a stupid compiler like GCC and want to mix a ponter to long with a pointer to int, which technically is the exact same thing, but GCC doesnt like it, but that is not an issue here). And Windows doesn't have it either.

File: drivers/input/mouclass/mouclass.c [hunk 14]
```diff
@@ -297,7 +297,7 @@ CreateClassDeviceObject(
 	DriverExtension = IoGetDriverObjectExtension(DriverObject, DriverObject);
 	DeviceNameU.Length = 0;
 	DeviceNameU.MaximumLength =
-		wcslen(L"\\Device\\") * sizeof(WCHAR)    /* "\Device\" */
+		(USHORT)wcslen(L"\\Device\\") * sizeof(WCHAR)    /* "\Device\" */
```
Comment (HBelusca) [inline drivers/input/mouclass/mouclass.c:300]:
```suggestion
		(USHORT)wcslen(L"\\Device\\") * sizeof(WCHAR) /* "\Device\" */
```

File: sdk/cmake/msvc.cmake [hunk 15]
```diff
@@ -88,6 +88,22 @@ add_compile_options(/wd4244 /wd4290 /wd4800 /wd4200 /wd4214)
 # FIXME: Temporarily disable C4018 until we fix more of the others. CORE-10113
 add_compile_options(/wd4018)
 
+# Allow all warnings on msbuild/VS IDE
+if (MSVC_IDE)
```
Comment (HBelusca) [inline sdk/cmake/msvc.cmake:92]:
```suggestion
if(MSVC_IDE)
```

File: sdk/cmake/msvc.cmake [hunk 16]
```diff
@@ -88,6 +88,22 @@ add_compile_options(/wd4244 /wd4290 /wd4800 /wd4200 /wd4214)
...
+    set(ALLOW_WARNINGS TRUE)
+endif()
+
+# On x86 Debug builds, if it's not Clang-CL or msbuild, treat all warnings as errors
+if ((ARCH STREQUAL "i386") AND (CMAKE_BUILD_TYPE STREQUAL "Debug") AND (NOT USE_CLANG_CL) AND (NOT MSVC_IDE))
```
Comment (HBelusca) [inline sdk/cmake/msvc.cmake:97]:
```suggestion
if((ARCH STREQUAL "i386") AND (CMAKE_BUILD_TYPE STREQUAL "Debug") AND (NOT USE_CLANG_CL) AND (NOT MSVC_IDE))
```

File: sdk/cmake/msvc.cmake [hunk 17]
```diff
@@ -88,6 +88,22 @@ add_compile_options(/wd4244 /wd4290 /wd4800 /wd4200 /wd4214)
...
+    set(TREAT_ALL_WARNINGS_AS_ERRORS=TRUE)
+endif()
+
+# Define ALLOW_WARNINGS=TRUE on the cmake/configure command line to bypass errors
+if (ALLOW_WARNINGS)
```
Comment (HBelusca) [inline sdk/cmake/msvc.cmake:102]:
```suggestion
if(ALLOW_WARNINGS)
```

File: sdk/cmake/msvc.cmake [hunk 18]
```diff
@@ -88,6 +88,22 @@ add_compile_options(/wd4244 /wd4290 /wd4800 /wd4200 /wd4214)
...
+    # Nothing
+elseif (TREAT_ALL_WARNINGS_AS_ERRORS)
```
Comment (HBelusca) [inline sdk/cmake/msvc.cmake:104]:
```suggestion
elseif(TREAT_ALL_WARNINGS_AS_ERRORS)
```

**Comment by JoachimHenze** [comment]
>> @tkreuzer "turns all warnings (except static analysis warnings) into errors."
Have you tested a build in MSVC Release configuration via
configure -DCMAKE_BUILD_TYPE=Release
Those traditionally have more warnings than the debug builds.
I wouldn't want you to break the Release config.

**Review by learn-more — APPROVED** [review]
lgtm

**Comment by tkreuzer** [comment]
> 
> 
> > > Have you tested a build in MSVC Release configuration via
> > > configure -DCMAKE_BUILD_TYPE=Release
> > > Those traditionally have more warnings than the debug builds.
> > > I wouldn't want you to break the Release config.

Sure. That is why I enabled MSVC release builds on GitHub. See the passed checks below.
